# Generated by Django 6.1.1 on 2026-09-15 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_ended_at_string_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
